# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

steps:
- task: DocFxTask@0
  inputs:
    solution: 'docfx.json'
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/_site/'
    azureSubscription: 'Equihira(f033c3c5-09e9-49c8-97d6-f60a79b20c1d)'
    Destination: 'AzureBlob'
    storage: 'altazion'
    ContainerName: 'aide-publique'
    BlobPrefix: 'dev/'

