name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@v1.0.0
      name: Compilation DocFX
      with: 
        args: docfx.json
    - uses: maxheld83/ghpages@master
      name: Publication sur la branche gh-pages
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
