name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@v0.1.0
      name: Compilation DocFX
      with: 
        args: docfx.json
    - name: Azure Storage Action
      uses: lauchacarro/Azure-Storage-Action@v1.1
      with:
        # Connection String of the Azure Storage Container
        connection-string: ${{ secrets.AZSTRAGE_CNSTRING }}
        # Folder what contains the files for upload to Storage Container
        folder: aide-dev
        # Name of Blob Container Storage
        blob-container-name: aide-publique
        # Enabled static website
        enabled-static-website: false
    - uses: maxheld83/ghpages@master
      name: Publication sur la branche gh-pages
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
